version: '2'
services:

  hotel-app:
    build: ./app/
    ports:
      - "8080:8080"
    network_mode: bridge

  selenoid:
    image: "aerokube/selenoid:latest-release"
    ports:
      - "4444:4444"
    volumes:
      - "/selenoid/:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: bridge
  hotel-test:
    build: .
    ports:
      - "9999:9999"
    network_mode: bridge
    links:
      - hotel-app
      - selenoid
    depends_on:
      - hotel-app
      - selenoid